version: "3"

services:
  graphdb:
    image: arangodb:3.8.6
    platform: linux/amd64
    environment:
      - ARANGO_ROOT_PASSWORD=
    ports:
      - "8529:8529"
    volumes:
      - resoto_graphdb_data:/var/lib/arangodb3
    ulimits:
      nofile:
        soft: 32768
        hard: 65535
  tsdb:
    image: prom/prometheus:v2.33.4
    ports:
      - "9090:9090"
    volumes:
      - ./dockerV2/prometheus.yml:/etc/prometheus/prometheus.yml
      - resoto_tsdb_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=730d
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
  resotocore:
    image: somecr.io/someengineering/resotocore:edge
    depends_on:
      - graphdb
    ports:
      - "8900:8900"
    environment:
      - PSK
      - RESOTO_VERBOSE
      - RESOTO_LOG_TEXT
      - RESOTOCORE_GRAPHDB_SERVER=http://graphdb:8529
      # Resoto will create a new database and user with this password using the root account
      - RESOTOCORE_GRAPHDB_PASSWORD=changeme
    command:
      - --override
      - resotocore.api.web_hosts=resotocore
      - resotocore.api.host_certificate.common_name=resotocore
      - resotocore.api.host_certificate.san_dns_names=resotocore
      - resotocore.api.tsdb_proxy_url=http://tsdb:9090
      - resotocore.api.ui_path=/usr/local/resoto/ui/
      - resotocore.runtime.start_collect_on_subscriber_connect=true
    restart: always
    stop_grace_period: 2m
  resotoworker:
    image: somecr.io/someengineering/resotoworker:edge
    depends_on:
      - resotocore
    ports:
      - 9956:9956
    environment:
      - PSK
      - RESOTO_VERBOSE
      - RESOTO_LOG_TEXT
      - RESOTOWORKER_RESOTOCORE_URI=https://resotocore:8900
    restart: always
    stop_grace_period: 2m
  resotometrics:
    image: somecr.io/someengineering/resotometrics:edge
    depends_on:
      - resotocore
    ports:
      - 9955:9955
    environment:
      - PSK
      - RESOTO_VERBOSE
      - RESOTO_LOG_TEXT
      - RESOTOMETRICS_RESOTOCORE_URI=https://resotocore:8900
    restart: always
    stop_grace_period: 2m
  resotoshell:
    # This container is not started by default. To start a shell use this command:
    # $> docker compose run --rm resotoshell
    image: somecr.io/someengineering/resotoshell:edge
    profiles:
      - do-not-start
    depends_on:
      - resotocore
    environment:
      - PSK
      - RESOTOSHELL_RESOTOCORE_URI=https://resotocore:8900
    restart: always
    stop_grace_period: 2m
  resotoshell-server:
    # This container can be used as jump target to start a shell.
    # Find the ID of the shell server and exec into it
    # $> docker ps -f name=resoto_resotoshell-server_1 --format "{{.ID}}"
    # $> docker exec -it <ID> resh
    #
    # Or to do it in one step
    # $> docker exec -it $(docker ps -f name=resoto_resotoshell-server_1 --format "{{.ID}}") resh
    image: somecr.io/someengineering/resotoshell:edge
    depends_on:
      - resotocore
    environment:
      - PSK
      - RESOTOSHELL_RESOTOCORE_URI=https://resotocore:8900
    command:
      - --wait
    restart: always
    stop_grace_period: 2m
volumes:
  resoto_graphdb_data:
  resoto_tsdb_data:
