{{- $name := printf "%s%s" (include "cloudkeeper.fullname" .) "-psk" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "cloudkeeper.labels" . | nindent 4 }}
data:
  # Check if the psk exists already (e.g. helm upgrade)
{{- $existingPskSecret := lookup "v1" "Secret" .Release.Namespace $name }}

{{- if not $existingPskSecret }}
  psk: {{ randAlphaNum 32 | b64enc | quote }}
{{- else }}
# psk does exist on cluster, build an object with the existing values
  psk: {{ index $existingPskSecret.data "psk" | quote }}
{{- end }}