apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudkeeper.fullname" . }}-ckworker
  labels:
    cloudkeeper: worker
    {{- include "cloudkeeper.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      cloudkeeper: worker
      {{- include "cloudkeeper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        cloudkeeper: worker
        {{- include "cloudkeeper.selectorLabels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cloudkeeper.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"

          args:
          - --collector
          - {{ .Values.ckworker.collector }}
          - --ckcore-uri
          - http://{{ include "cloudkeeper.fullname" . }}-ckcore:{{ .Values.ckcore.service.port }}
          - --ckcore-ws-uri
          - ws://{{ include "cloudkeeper.fullname" . }}-ckcore:{{ .Values.ckcore.service.port }}
          {{- if .Values.ckworker.extraArgs }}
          {{- toYaml .Values.ckworker.extraArgs | nindent 10 }}
          {{- end }}
          env:
            - name: START_STACK
              value: "false"
            - name: START_CKWORKER
              value: "true"
          {{- if .Values.ckworker.extraEnv }}
          {{- toYaml .Values.ckworker.extraEnv | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          readinessProbe:
            httpGet:
              path: /health
              port: 9956
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
    {{- if .Values.ckworker.volumeMounts }}
          volumeMounts:
    {{- toYaml .Values.ckworker.volumeMounts | nindent 12 }}
    {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- if .Values.ckworker.volumes }}
      volumes:
{{ toYaml .Values.ckworker.volumes | nindent 8 }}
{{- end }}
