apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resoto.fullname" . }}-resotometrics
  labels:
    resoto: metrics
    {{- include "resoto.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '9955'
spec:
  replicas: 1
  selector:
    matchLabels:
      resoto: metrics
      {{- include "resoto.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        resoto: metrics
        {{- include "resoto.selectorLabels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "resoto.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repositoryFolder }}/resotometrics:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - --resotocore-uri
          - https://{{ include "resoto.fullname" . }}-resotocore:8900
          {{- if .Values.resotometrics.extraArgs }}
          {{- toYaml .Values.resotometrics.extraArgs | nindent 10 }}
          {{- end }}
          env:
          - name: PSK
            valueFrom:
              secretKeyRef:
                name: {{ include "resoto.fullname" . }}-psk
                key: "psk"
          {{- if .Values.resotoworker.extraEnv }}
          {{- toYaml .Values.resotoworker.extraEnv | nindent 12 }}
          {{- end }}
          ports:
            - name: https
              containerPort: 9955
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: https
              scheme: HTTPS
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
