# Note: the testing steps are the same as ckcore_test but with different python runner
#       Reason: coverage under pypy is super slow!
name: Coverage (ckcore)
on:
  push:
    paths:
      - 'ckcore/**'
      - '.github/**'

jobs:
  lint-and-test:
    name: "Coverage (ckcore)"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ckcore
    services:
      arangodb:
        image: arangodb:3.8.3
        env:
          ARANGO_ROOT_PASSWORD: root
        ports:
          - 8529:8529
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Restore dependency cache
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{runner.os}}-pip-${{hashFiles('requirements.txt')}}-${{hashFiles('requirements-dev.txt')}}-${{hashFiles('requirements-test.txt')}}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --editable ../cklib
          pip install -r requirements-test.txt
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          coverage run --source core -m pytest
          coverage combine
          coverage xml
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          flags: ckcore

