# Note: the testing steps are the same as fixcore_test but with different python runner
#       Reason: coverage under pypy is super slow!
name: Coverage (fixcore)
on:
  push:
    branches:
      - main
    paths:
      - 'fixcore/**'
      - '.github/**'
      - 'requirements-all.txt'
  pull_request:
    paths:
      - 'fixcore/**'
      - '.github/**'
      - 'requirements-all.txt'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  fixcore-coverage:
    name: "Coverage (fixcore)"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fixcore
    services:
      arangodb:
        image: arangodb:3.8.8
        env:
          ARANGO_NO_AUTH: 1
        ports:
          - 8529:8529
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: Restore dependency cache
        uses: actions/cache@v4
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{runner.os}}-pip-${{hashFiles('./fixcore/pyproject.toml')}}-${{hashFiles('./fixcore/requirements-all.txt')}}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements-all.txt
          pip install ../fixlib
      - name: Run Tests
        env:
          FIXCORE_ANALYTICS_OPT_OUT: true
        run: |
          coverage run --source fixcore -m pytest
          coverage combine
          coverage xml
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: fixcore/coverage.xml
          flags: fixcore

