name: Test k8s helm chart

on:
    push:
        tags:
            - "*.*.*"
        branches:
            - main
    pull_request:
        paths:
            - 'kubernetes/**'
            - '.github/workflows/k8s-build.yml'
    workflow_dispatch:

jobs:
    build:
        name: Build Docker Images
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Set up Helm
              uses: azure/setup-helm@v1
              with:
                version: v3.4.0

            - uses: engineerd/setup-kind@v0.5.0
            - name: Testing
              run: |
                  NO_START_KIND=1 IMAGE_TAG=latest bash -x ./kubernetes/setup-kind.sh
                  # make sure we get the example collector in a reasonable time.
                  timeout 1m /bin/bash -c "until echo kind |kubectl --namespace cloudkeeper exec -i deploy/cloudkeeper-ckcore -- cksh --stdin|grep example_resource; do sleep 1; done"
            - name: Debug info on failure
              if: ${{ failure() }}
              run: |
                  kubectl get all --namespace cloudkeeper
                  echo "Core logs:"
                  kubectl logs --namespace cloudkeeper deploy/cloudkeeper-ckcore
                  echo "Worker logs:"
                  kubectl logs --namespace cloudkeeper deploy/cloudkeeper-ckworker
                  echo "Metrics logs:"
                  kubectl logs --namespace cloudkeeper deploy/cloudkeeper-ckmetrics
