name: Test k8s helm chart

on:
    push:
        tags:
            - "*.*.*"
        branches:
            - main
    pull_request:
        paths:
            - 'kubernetes/**'
            - '.github/workflows/k8s-build.yml'
    workflow_dispatch:

jobs:
    build:
        name: Test k8s helm chart
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Set up Helm
              uses: azure/setup-helm@v1
              with:
                version: v3.8.1

            - uses: engineerd/setup-kind@v0.5.0
              with:
                version: "v0.12.0"
            - name: Testing
              run: |
                  NO_START_KIND=1 IMAGE_TAG=edge bash -x ./kubernetes/setup-kind.sh
                  # make sure we get the example collector in a reasonable time.
                  timeout 1m /bin/bash -c "until echo 'workflows run collect; sleep 5; kind' |kubectl --namespace resoto exec -i deploy/resoto-resotocore -- resh --stdin|grep example_resource; do sleep 1; done"
            - name: Debug info on failure
              if: ${{ failure() }}
              run: |
                  echo "Nodes:"
                  kubectl get nodes -o wide
                  echo "Cluster state:"
                  kubectl describe all --namespace resoto
                  echo "Core logs:"
                  kubectl logs --namespace resoto deploy/resoto-resotocore
                  echo "Worker logs:"
                  kubectl logs --namespace resoto deploy/resoto-resotoworker
                  echo "Metrics logs:"
                  kubectl logs --namespace resoto deploy/resoto-resotometrics
