# Check the model of all collector plugins for consistency.
name: Model Check
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'resotolib/**'
      - 'plugins/aws/**'
      - 'plugins/azure/**'
      - 'plugins/digitalocean/**'
      - 'plugins/example_collector/**'
      - 'plugins/gcp/**'
      - 'plugins/github/**'
      - 'plugins/k8s/**'
      - 'plugins/onelogin/**'
      - 'plugins/onprem/**'
      - 'plugins/slack/**'
      - 'plugins/vsphere/**'
      - '.github/**'
      - 'requirements-all.txt'
  workflow_dispatch:

jobs:
  model:
    name: "model"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Restore dependency cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{hashFiles('./resotolib/pyproject.toml')}}-${{hashFiles('./resotolib/requirements-test.txt')}}-${{hashFiles('./plugins/**/pyproject.toml')}}

          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-test.txt
          pip install resotolib/ plugins/aws/ plugins/azure plugins/digitalocean/ plugins/dockerhub/ plugins/example_collector/ plugins/gcp/ plugins/github/ plugins/k8s/ plugins/onelogin/ plugins/onprem/ plugins/posthog/ plugins/random/ plugins/scarf/ plugins/slack/ plugins/vsphere/

      - name: Run tests
        working-directory: ./resotolib
        env:
          MODEL_CHECK: "true"
        run: pytest test/core/model_check_test.py
