# Check the model of all collector plugins for consistency.
name: Model Check
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'resotolib/**'
      - 'plugins/aws/**'
      - 'plugins/digitalocean/**'
      - 'plugins/example_collector/**'
      - 'plugins/gcp/**'
      - 'plugins/github/**'
      - 'plugins/k8s/**'
      - 'plugins/onelogin/**'
      - 'plugins/onprem/**'
      - 'plugins/slack/**'
      - 'plugins/vsphere/**'
      - '.github/**'
  workflow_dispatch:

jobs:
  aws:
    name: "aws"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Restore dependency cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: $\{\{runner.os}}-pip-$\{\{hashFiles('setup.py')}}
          restore-keys: |
            $\{\{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --editable resotolib/
          pip install --upgrade --editable plugins/aws/
          pip install --upgrade --editable plugins/digitalocean/
          pip install --upgrade --editable plugins/example_collector/
          pip install --upgrade --editable plugins/gcp/
          pip install --upgrade --editable plugins/github/
          pip install --upgrade --editable plugins/k8s/
          pip install --upgrade --editable plugins/onelogin/
          pip install --upgrade --editable plugins/onprem/
          pip install --upgrade --editable plugins/slack/
          pip install --upgrade --editable plugins/vsphere/
          pip install pytest

      - name: Run tests
        working-directory: ./resotolib
        env:
          MODEL_CHECK: "true"
        run: pytest test/core/model_check_test.py
