# Note: the testing steps are the same as resotocore_test but with different python runner
#       Reason: coverage under pypy is super slow!
name: Coverage (resotocore)
on:
  push:
    branches:
      - main
    paths:
      - 'resotocore/**'
      - '.github/**'
  pull_request:
    paths:
      - 'resotocore/**'
      - '.github/**'

jobs:
  lint-and-test:
    name: "Coverage (resotocore)"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./resotocore
    services:
      arangodb:
        image: arangodb:3.8.3
        env:
          ARANGO_NO_AUTH: 1
        ports:
          - 8529:8529
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Restore dependency cache
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: $\{\{runner.os}}-cache-$\{\{hashFiles('pyproject.toml')}}-$\{\{hashFiles('poetry.lock')}}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry nox
      - name: Run Tests
        run: |
          nox -rs coverage_ci
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: resotocore/coverage.xml
          flags: resotocore

